name: HIL Checks

on:
  workflow_call:
    inputs:
      project-yaml:
        required: true
        type: string
        description: 'Project Yaml file that consists of build and check configurations'
      user-yaml:
        required: true
        type: string
        description: 'User Yaml file with list of build and checks to be executed'
      decrypt-secrets:
        required: false
        type: string
        description: 'script for decrypting the secret file that consist of SSID passphrase'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# permissions:
#   contents: write
    
jobs:
  setup:
    runs-on: ubuntu-24.04

    container:
      image: docker.io/ifxmakers/makers-docker:latest

      # image: ghcr.io/infineon/makers-docker:latest
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.github_token }}

      volumes:
        - .:/myLocalWorkingDir:rw
      options: --cpus 1

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set strategy matrix (get all hil checks)
        id: set-matrix
        run: |
          eval $(python3 extras/makers-devops/src/python/code_checks/codeChecks.py --projectYAML "${{ inputs.project-yaml }}" --userYAML "${{ inputs.user-yaml }}" --getAllHILChecks)

      - name: Append HIL Checks Output to Summary
        run: |
          echo "## ðŸ“œ Test Quality Report" >> $GITHUB_STEP_SUMMARY

    outputs:
      checks: ${{ steps.set-matrix.outputs.checks }}
      decrypt-secrets: ${{ inputs.decrypt-secrets }}

  setupHilEnv:
    runs-on:
      - self-hosted
      - X64
      - Linux
    needs: setup
    steps:
      - name: Setup makers-hil deploy environment
        run: |
          switch_makers_hil.sh deploy

  hilChecks:
    runs-on:
      - self-hosted
      - X64
      - Linux
    needs: [setup, setupHilEnv]

    strategy:
      fail-fast: false
      max-parallel: 3

      matrix:
        checks: ${{ fromJson(needs.setup.outputs.checks) }}

    steps:
      - name: Checkout repository (recursive submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
          fetch-depth: 0

      - name: Decrypt secret file that consists of SSID passphrase
        if: ${{ needs.setup.outputs.decrypt-secrets != '' }}
        run: |
          ${{ needs.setup.outputs.decrypt-secrets }}
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      
      - name: Run HIL check (${{ matrix.checks }})
        timeout-minutes: 10
        run: |
          echo "Workflow has these parameters :"
          echo "matrix.checks   : ${{ matrix.checks }}"
          echo ""

          hilChecks.py --projectYAML "${{ inputs.project-yaml }}" --userYAML "${{ inputs.user-yaml }}" --runCheck ${{ matrix.checks }} --dockerTag=latest  2>&1 | tee output.log

      - name: Prepare HIL results for artifact upload
        if: success() || failure()
        run: |
          mkdir -p _results
          cp output.log _results/

      - name: Archive HIL check reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.checks }}
          path: _results

      - name: Append HIL checks output to summary
        if: success() || failure()
        run: |
          echo "<test_results>" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          awk '/Unity test run 1 of 1/,/Number of ignored tests/' output.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "</test_results>" >> $GITHUB_STEP_SUMMARY
